# Generated by Django 3.1.6 on 2021-03-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_auto_20210223_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/static/images/download.png', null=True, upload_to=''),
        ),
    ]
